In [1]:
%pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Using cached absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from tensorflow) (25.0)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\user\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\user\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\user\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\user\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Using cached grpcio-1.83.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Using cached keras-3.15.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from tensorflow) (2.5.1)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Using cached h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Using cached ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\user\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\user\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Collecting namex (from keras>=3.12.0->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Using cached optree-0.19.1-cp313-cp313-win_amd64.whl.metadata (32 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\user\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\user\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\user\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.8/351.2 MB 6.4 MB/s eta 0:00:56
   ---------------------------------------- 2.9/351.2 MB 8.9 MB/s eta 0:00:39
    --------------------------------------- 4.7/351.2 MB 8.7 MB/s eta 0:00:40
    --------------------------------------- 5.8/351.2 MB 7.8 MB/s eta 0:00:45
    --------------------------------------- 6.6/351.2 MB 7.1 MB/s eta 0:00:49
    --------------------------------------- 7.1/351.2 MB 6.1 MB/s eta 0:00:57
    --------------------------------------- 7.3/351.2 MB 5.6 MB/s eta 0:01:01
    --------------------------------------- 7.9/351.2 MB 4.9 MB/s eta 0:01:10
    --------------------------------------- 8.4/351.2 MB 4.6 MB/s eta 0:01:15
    --------------------------------------- 8.7/351.2 MB 4.5 MB/s eta 0:01:17
   - -------------------------------------- 9.2/351.2 MB 4.3 MB/s eta 0:01:20
   - -------------------------------------- 9.7/351.2 MB 4.1 MB/s eta 0:01:23
   - -------------------------------------- 10.5/351.2 MB 4.0 MB/s eta 0:01:26
   - -------------------------------------- 11.0/351.2 MB 3.9 MB/s eta 0:01:28
   - -------------------------------------- 11.5/351.2 MB 3.8 MB/s eta 0:01:30
   - -------------------------------------- 12.1/351.2 MB 3.7 MB/s eta 0:01:31
   - -------------------------------------- 12.6/351.2 MB 3.7 MB/s eta 0:01:32
   - -------------------------------------- 13.4/351.2 MB 3.7 MB/s eta 0:01:33
   - -------------------------------------- 13.9/351.2 MB 3.6 MB/s eta 0:01:33
   - -------------------------------------- 14.7/351.2 MB 3.6 MB/s eta 0:01:34
   - -------------------------------------- 15.2/351.2 MB 3.6 MB/s eta 0:01:34
   - -------------------------------------- 16.0/351.2 MB 3.6 MB/s eta 0:01:34
   - -------------------------------------- 16.8/351.2 MB 3.6 MB/s eta 0:01:34
   - -------------------------------------- 17.3/351.2 MB 3.6 MB/s eta 0:01:34
   -- ------------------------------------- 18.1/351.2 MB 3.6 MB/s eta 0:01:34
   -- ------------------------------------- 18.9/351.2 MB 3.6 MB/s eta 0:01:34
   -- ------------------------------------- 19.7/351.2 MB 3.6 MB/s eta 0:01:33
   -- ------------------------------------- 20.4/351.2 MB 3.6 MB/s eta 0:01:32
   -- ------------------------------------- 21.5/351.2 MB 3.6 MB/s eta 0:01:32
   -- ------------------------------------- 22.3/351.2 MB 3.6 MB/s eta 0:01:31
   -- ------------------------------------- 23.1/351.2 MB 3.7 MB/s eta 0:01:30
   -- ------------------------------------- 23.9/351.2 MB 3.7 MB/s eta 0:01:30
   -- ------------------------------------- 24.9/351.2 MB 3.7 MB/s eta 0:01:29
   -- ------------------------------------- 25.7/351.2 MB 3.7 MB/s eta 0:01:28
   --- ------------------------------------ 26.7/351.2 MB 3.7 MB/s eta 0:01:27
   --- ------------------------------------ 27.5/351.2 MB 3.7 MB/s eta 0:01:27
   --- ------------------------------------ 28.3/351.2 MB 3.8 MB/s eta 0:01:26
   --- ------------------------------------ 29.4/351.2 MB 3.8 MB/s eta 0:01:25
   --- ------------------------------------ 30.4/351.2 MB 3.8 MB/s eta 0:01:24
   --- ------------------------------------ 31.5/351.2 MB 3.8 MB/s eta 0:01:24
   --- ------------------------------------ 32.5/351.2 MB 3.9 MB/s eta 0:01:23
   --- ------------------------------------ 33.6/351.2 MB 3.9 MB/s eta 0:01:22
   --- ------------------------------------ 34.6/351.2 MB 3.9 MB/s eta 0:01:21
   ---- ----------------------------------- 35.4/351.2 MB 3.9 MB/s eta 0:01:21
   ---- ----------------------------------- 36.4/351.2 MB 4.0 MB/s eta 0:01:20
   ---- ----------------------------------- 37.5/351.2 MB 4.0 MB/s eta 0:01:19
   ---- ----------------------------------- 38.5/351.2 MB 4.0 MB/s eta 0:01:18
   ---- ----------------------------------- 39.6/351.2 MB 4.0 MB/s eta 0:01:18
   ---- ----------------------------------- 40.9/351.2 MB 4.1 MB/s eta 0:01:17
   ---- ----------------------------------- 41.9/351.2 MB 4.1 MB/s eta 0:01:16
   ---- ----------------------------------- 43.3/351.2 MB 4.1 MB/s eta 0:01:15
   ----- ---------------------------------- 44.3/351.2 MB 4.2 MB/s eta 0:01:14
   ----- ---------------------------------- 45.6/351.2 MB 4.2 MB/s eta 0:01:13
   ----- ---------------------------------- 46.7/351.2 MB 4.2 MB/s eta 0:01:12
   ----- ---------------------------------- 48.0/351.2 MB 4.3 MB/s eta 0:01:12
   ----- ---------------------------------- 48.8/351.2 MB 4.3 MB/s eta 0:01:11
   ----- ---------------------------------- 49.5/351.2 MB 4.2 MB/s eta 0:01:12
   ----- ---------------------------------- 50.1/351.2 MB 4.2 MB/s eta 0:01:12
   ----- ---------------------------------- 50.9/351.2 MB 4.2 MB/s eta 0:01:12
   ----- ---------------------------------- 51.6/351.2 MB 4.2 MB/s eta 0:01:12
   ----- ---------------------------------- 52.4/351.2 MB 4.2 MB/s eta 0:01:12
   ------ --------------------------------- 53.2/351.2 MB 4.2 MB/s eta 0:01:12
   ------ --------------------------------- 54.0/351.2 MB 4.2 MB/s eta 0:01:11
   ------ --------------------------------- 54.8/351.2 MB 4.2 MB/s eta 0:01:11
   ------ --------------------------------- 55.6/351.2 MB 4.2 MB/s eta 0:01:11
   ------ --------------------------------- 56.6/351.2 MB 4.2 MB/s eta 0:01:11
   ------ --------------------------------- 57.4/351.2 MB 4.2 MB/s eta 0:01:11
   ------ --------------------------------- 58.2/351.2 MB 4.2 MB/s eta 0:01:11
   ------ --------------------------------- 59.2/351.2 MB 4.2 MB/s eta 0:01:10
   ------ --------------------------------- 60.0/351.2 MB 4.2 MB/s eta 0:01:10
   ------ --------------------------------- 60.8/351.2 MB 4.2 MB/s eta 0:01:10
   ------- -------------------------------- 61.6/351.2 MB 4.2 MB/s eta 0:01:10
   ------- -------------------------------- 62.7/351.2 MB 4.2 MB/s eta 0:01:10
   ------- -------------------------------- 63.4/351.2 MB 4.2 MB/s eta 0:01:09
   ------- -------------------------------- 64.5/351.2 MB 4.2 MB/s eta 0:01:09
   ------- -------------------------------- 65.5/351.2 MB 4.2 MB/s eta 0:01:09
   ------- -------------------------------- 66.6/351.2 MB 4.2 MB/s eta 0:01:08
   ------- -------------------------------- 67.6/351.2 MB 4.2 MB/s eta 0:01:08
   ------- -------------------------------- 68.7/351.2 MB 4.2 MB/s eta 0:01:07
   ------- -------------------------------- 69.7/351.2 MB 4.2 MB/s eta 0:01:07
   -------- ------------------------------- 70.8/351.2 MB 4.3 MB/s eta 0:01:06
   -------- ------------------------------- 71.8/351.2 MB 4.3 MB/s eta 0:01:06
   -------- ------------------------------- 72.9/351.2 MB 4.3 MB/s eta 0:01:06
   -------- ------------------------------- 74.2/351.2 MB 4.3 MB/s eta 0:01:05
   -------- ------------------------------- 75.2/351.2 MB 4.3 MB/s eta 0:01:05
   -------- ------------------------------- 76.3/351.2 MB 4.3 MB/s eta 0:01:04
   -------- ------------------------------- 77.3/351.2 MB 4.3 MB/s eta 0:01:04
   -------- ------------------------------- 78.6/351.2 MB 4.3 MB/s eta 0:01:03
   --------- ------------------------------ 79.4/351.2 MB 4.3 MB/s eta 0:01:03
   --------- ------------------------------ 80.5/351.2 MB 4.3 MB/s eta 0:01:03
   --------- ------------------------------ 81.3/351.2 MB 4.3 MB/s eta 0:01:03
   --------- ------------------------------ 82.3/351.2 MB 4.4 MB/s eta 0:01:02
   --------- ------------------------------ 83.4/351.2 MB 4.4 MB/s eta 0:01:02
   --------- ------------------------------ 84.4/351.2 MB 4.4 MB/s eta 0:01:02
   --------- ------------------------------ 85.5/351.2 MB 4.4 MB/s eta 0:01:01
   --------- ------------------------------ 86.5/351.2 MB 4.4 MB/s eta 0:01:01
   --------- ------------------------------ 87.6/351.2 MB 4.4 MB/s eta 0:01:01
   ---------- ----------------------------- 88.3/351.2 MB 4.4 MB/s eta 0:01:00
   ---------- ----------------------------- 89.4/351.2 MB 4.4 MB/s eta 0:01:00
   ---------- ----------------------------- 90.4/351.2 MB 4.4 MB/s eta 0:01:00
   ---------- ----------------------------- 91.8/351.2 MB 4.4 MB/s eta 0:00:59
   ---------- ----------------------------- 92.8/351.2 MB 4.4 MB/s eta 0:00:59
   ---------- ----------------------------- 94.1/351.2 MB 4.4 MB/s eta 0:00:58
   ---------- ----------------------------- 95.2/351.2 MB 4.4 MB/s eta 0:00:58
   ---------- ----------------------------- 96.5/351.2 MB 4.5 MB/s eta 0:00:58
   ----------- ---------------------------- 97.5/351.2 MB 4.5 MB/s eta 0:00:57
   ----------- ---------------------------- 98.6/351.2 MB 4.5 MB/s eta 0:00:57
   ----------- ---------------------------- 99.4/351.2 MB 4.5 MB/s eta 0:00:57
   ----------- ---------------------------- 100.4/351.2 MB 4.5 MB/s eta 0:00:57
   ----------- ---------------------------- 101.2/351.2 MB 4.5 MB/s eta 0:00:56
   ----------- ---------------------------- 102.2/351.2 MB 4.5 MB/s eta 0:00:56
   ----------- ---------------------------- 103.0/351.2 MB 4.5 MB/s eta 0:00:56
   ----------- ---------------------------- 104.1/351.2 MB 4.5 MB/s eta 0:00:56
   ----------- ---------------------------- 105.1/351.2 MB 4.5 MB/s eta 0:00:56
   ------------ --------------------------- 106.2/351.2 MB 4.5 MB/s eta 0:00:55
   ------------ --------------------------- 107.2/351.2 MB 4.5 MB/s eta 0:00:55
   ------------ --------------------------- 108.3/351.2 MB 4.5 MB/s eta 0:00:55
   ------------ --------------------------- 109.3/351.2 MB 4.5 MB/s eta 0:00:54
   ------------ --------------------------- 110.1/351.2 MB 4.5 MB/s eta 0:00:54
   ------------ --------------------------- 110.9/351.2 MB 4.5 MB/s eta 0:00:54
   ------------ --------------------------- 111.7/351.2 MB 4.5 MB/s eta 0:00:54
   ------------ --------------------------- 112.7/351.2 MB 4.5 MB/s eta 0:00:54
   ------------ --------------------------- 113.5/351.2 MB 4.5 MB/s eta 0:00:54
   ------------- -------------------------- 114.3/351.2 MB 4.5 MB/s eta 0:00:53
   ------------- -------------------------- 115.3/351.2 MB 4.5 MB/s eta 0:00:53
   ------------- -------------------------- 116.1/351.2 MB 4.5 MB/s eta 0:00:53
   ------------- -------------------------- 117.2/351.2 MB 4.5 MB/s eta 0:00:53
   ------------- -------------------------- 118.0/351.2 MB 4.5 MB/s eta 0:00:53
   ------------- -------------------------- 119.0/351.2 MB 4.5 MB/s eta 0:00:52
   ------------- -------------------------- 119.8/351.2 MB 4.5 MB/s eta 0:00:52
   ------------- -------------------------- 120.8/351.2 MB 4.5 MB/s eta 0:00:52
   ------------- -------------------------- 121.9/351.2 MB 4.5 MB/s eta 0:00:52
   -------------- ------------------------- 122.9/351.2 MB 4.5 MB/s eta 0:00:51
   -------------- ------------------------- 123.7/351.2 MB 4.5 MB/s eta 0:00:51
   -------------- ------------------------- 124.8/351.2 MB 4.5 MB/s eta 0:00:51
   -------------- ------------------------- 125.8/351.2 MB 4.5 MB/s eta 0:00:51
   -------------- ------------------------- 127.1/351.2 MB 4.5 MB/s eta 0:00:50
   -------------- ------------------------- 128.2/351.2 MB 4.5 MB/s eta 0:00:50
   -------------- ------------------------- 129.2/351.2 MB 4.5 MB/s eta 0:00:50
   -------------- ------------------------- 130.3/351.2 MB 4.5 MB/s eta 0:00:49
   -------------- ------------------------- 131.6/351.2 MB 4.5 MB/s eta 0:00:49
   --------------- ------------------------ 132.6/351.2 MB 4.5 MB/s eta 0:00:49
   --------------- ------------------------ 134.0/351.2 MB 4.5 MB/s eta 0:00:48
   --------------- ------------------------ 135.0/351.2 MB 4.5 MB/s eta 0:00:48
   --------------- ------------------------ 136.1/351.2 MB 4.6 MB/s eta 0:00:48
   --------------- ------------------------ 137.4/351.2 MB 4.6 MB/s eta 0:00:47
   --------------- ------------------------ 138.7/351.2 MB 4.5 MB/s eta 0:00:47
   --------------- ------------------------ 139.7/351.2 MB 4.5 MB/s eta 0:00:47
   --------------- ------------------------ 140.2/351.2 MB 4.5 MB/s eta 0:00:48
   ---------------- ----------------------- 140.5/351.2 MB 4.5 MB/s eta 0:00:48
   ---------------- ----------------------- 141.0/351.2 MB 4.5 MB/s eta 0:00:47
   ---------------- ----------------------- 141.6/351.2 MB 4.5 MB/s eta 0:00:47
   ---------------- ----------------------- 142.1/351.2 MB 4.5 MB/s eta 0:00:47
   ---------------- ----------------------- 142.6/351.2 MB 4.5 MB/s eta 0:00:47
   ---------------- ----------------------- 143.1/351.2 MB 4.5 MB/s eta 0:00:47
   ---------------- ----------------------- 143.7/351.2 MB 4.5 MB/s eta 0:00:47
   ---------------- ----------------------- 144.2/351.2 MB 4.5 MB/s eta 0:00:47
   ---------------- ----------------------- 144.7/351.2 MB 4.5 MB/s eta 0:00:47
   ---------------- ----------------------- 145.5/351.2 MB 4.5 MB/s eta 0:00:46
   ---------------- ----------------------- 146.0/351.2 MB 4.5 MB/s eta 0:00:46
   ---------------- ----------------------- 146.5/351.2 MB 4.5 MB/s eta 0:00:46
   ---------------- ----------------------- 147.3/351.2 MB 4.5 MB/s eta 0:00:46
   ---------------- ----------------------- 147.8/351.2 MB 4.5 MB/s eta 0:00:46
   ---------------- ----------------------- 148.6/351.2 MB 4.5 MB/s eta 0:00:46
   ----------------- ---------------------- 149.4/351.2 MB 4.5 MB/s eta 0:00:45
   ----------------- ---------------------- 150.2/351.2 MB 4.5 MB/s eta 0:00:45
   ----------------- ---------------------- 151.0/351.2 MB 4.5 MB/s eta 0:00:45
   ----------------- ---------------------- 151.8/351.2 MB 4.5 MB/s eta 0:00:45
   ----------------- ---------------------- 152.6/351.2 MB 4.5 MB/s eta 0:00:45
   ----------------- ---------------------- 153.4/351.2 MB 4.5 MB/s eta 0:00:44
   ----------------- ---------------------- 154.1/351.2 MB 4.5 MB/s eta 0:00:44
   ----------------- ---------------------- 154.9/351.2 MB 4.5 MB/s eta 0:00:44
   ----------------- ---------------------- 156.0/351.2 MB 4.5 MB/s eta 0:00:44
   ----------------- ---------------------- 156.8/351.2 MB 4.5 MB/s eta 0:00:44
   ----------------- ---------------------- 157.8/351.2 MB 4.5 MB/s eta 0:00:43
   ------------------ --------------------- 158.9/351.2 MB 4.5 MB/s eta 0:00:43
   ------------------ --------------------- 159.6/351.2 MB 4.5 MB/s eta 0:00:43
   ------------------ --------------------- 160.7/351.2 MB 4.5 MB/s eta 0:00:43
   ------------------ --------------------- 161.5/351.2 MB 4.5 MB/s eta 0:00:42
   ------------------ --------------------- 162.5/351.2 MB 4.5 MB/s eta 0:00:42
   ------------------ --------------------- 163.6/351.2 MB 4.5 MB/s eta 0:00:42
   ------------------ --------------------- 164.6/351.2 MB 4.5 MB/s eta 0:00:42
   ------------------ --------------------- 165.7/351.2 MB 4.5 MB/s eta 0:00:41
   ------------------ --------------------- 166.7/351.2 MB 4.5 MB/s eta 0:00:41
   ------------------- -------------------- 167.8/351.2 MB 4.5 MB/s eta 0:00:41
   ------------------- -------------------- 168.8/351.2 MB 4.5 MB/s eta 0:00:41
   ------------------- -------------------- 170.1/351.2 MB 4.5 MB/s eta 0:00:40
   ------------------- -------------------- 171.2/351.2 MB 4.5 MB/s eta 0:00:40
   ------------------- -------------------- 172.2/351.2 MB 4.6 MB/s eta 0:00:40
   ------------------- -------------------- 173.3/351.2 MB 4.6 MB/s eta 0:00:40
   ------------------- -------------------- 174.3/351.2 MB 4.6 MB/s eta 0:00:39
   ------------------- -------------------- 175.4/351.2 MB 4.6 MB/s eta 0:00:39
   -------------------- ------------------- 176.7/351.2 MB 4.6 MB/s eta 0:00:39
   -------------------- ------------------- 178.0/351.2 MB 4.6 MB/s eta 0:00:38
   -------------------- ------------------- 179.0/351.2 MB 4.6 MB/s eta 0:00:38
   -------------------- ------------------- 180.4/351.2 MB 4.6 MB/s eta 0:00:38
   -------------------- ------------------- 181.1/351.2 MB 4.6 MB/s eta 0:00:38
   -------------------- ------------------- 181.9/351.2 MB 4.5 MB/s eta 0:00:38
   -------------------- ------------------- 182.7/351.2 MB 4.5 MB/s eta 0:00:38

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.35.1 which is incompatible.

In [48]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [49]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [50]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [51]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [52]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [53]:
# Min Max Scaler
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [54]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled , y, test_size = 0.25, random_state=42)

In [56]:
model = keras.Sequential([
    layers.Input(shape = (X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1, activation = "sigmoid")
])

In [57]:
model.compile(optimizer = 'sgd',loss='binary_crossentropy', metrics = ['accuracy'])

In [58]:
total = len(X_train)
# history_full = model.fit(X_train, y_train, epochs=100, batch_size=total, verbose=1)

In [59]:
history = model.fit(
    X_train.values, y_train.values,
    validation_data = (X_test.values, y_test.values),
    epochs = 100, batch_size = 4, verbose = 1
)
history_minibatch = model.fit(X_train, y_train, epochs=100, batch_size=100, verbose=1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 205ms/step - accuracy: 0.5833 - loss: 0.6823 - val_accuracy: 0.5000 - val_loss: 0.6600
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5833 - loss: 0.6811 - val_accuracy: 0.5000 - val_loss: 0.6606
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6667 - loss: 0.6799 - val_accuracy: 0.5000 - val_loss: 0.6612
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6667 - loss: 0.6788 - val_accuracy: 0.5000 - val_loss: 0.6617
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6667 - loss: 0.6780 - val_accuracy: 0.5000 - val_loss: 0.6623
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6667 - loss: 0.6765 - val_accuracy: 0.5000 - val_loss: 0.6629
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.6667 - loss: 0.6755 - val_accuracy: 0.5000 - val_loss: 0.6635
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6667 - loss: 0.6749 - val_accuracy: 0.5000 - val_loss: 0.6641
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6667 - loss: 0.6736 - val_accuracy: 0.5000 - val_loss: 0.6646
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6667 - loss: 0.6721 - val_accuracy: 0.5000 - val_loss: 0.6652
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6667 - loss: 0.6714 - val_accuracy: 0.5000 - val_loss: 0.6658
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.7500 - loss: 0.6702 - val_accuracy: 0.5000 - val_loss: 0.6663
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.7500 - loss: 0.6694 - val_accuracy: 0.5000 - val_loss: 0.6669
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7500 - loss: 0.6681 - val_accuracy: 0.5000 - val_loss: 0.6674
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.7500 - loss: 0.6683 - val_accuracy: 0.5000 - val_loss: 0.6680
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.7500 - loss: 0.6666 - val_accuracy: 0.5000 - val_loss: 0.6684
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.7500 - loss: 0.6651 - val_accuracy: 0.5000 - val_loss: 0.6689
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.7500 - loss: 0.6641 - val_accuracy: 0.5000 - val_loss: 0.6694
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7500 - loss: 0.6631 - val_accuracy: 0.5000 - val_loss: 0.6698
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.8333 - loss: 0.6618 - val_accuracy: 0.5000 - val_loss: 0.6702
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.8333 - loss: 0.6608 - val_accuracy: 0.5000 - val_loss: 0.6707
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8333 - loss: 0.6597 - val_accuracy: 0.5000 - val_loss: 0.6711
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.8333 - loss: 0.6595 - val_accuracy: 0.5000 - val_loss: 0.6715
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.8333 - loss: 0.6576 - val_accuracy: 0.5000 - val_loss: 0.6719
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.8333 - loss: 0.6568 - val_accuracy: 0.5000 - val_loss: 0.6723
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.8333 - loss: 0.6554 - val_accuracy: 0.5000 - val_loss: 0.6727
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.8333 - loss: 0.6543 - val_accuracy: 0.5000 - val_loss: 0.6731
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.8333 - loss: 0.6535 - val_accuracy: 0.5000 - val_loss: 0.6734
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.8333 - loss: 0.6520 - val_accuracy: 0.5000 - val_loss: 0.6738
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.8333 - loss: 0.6508 - val_accuracy: 0.5000 - val_loss: 0.6741
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.8333 - loss: 0.6503 - val_accuracy: 0.5000 - val_loss: 0.6745
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.8333 - loss: 0.6491 - val_accuracy: 0.5000 - val_loss: 0.6748
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.8333 - loss: 0.6476 - val_accuracy: 0.5000 - val_loss: 0.6752
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.8333 - loss: 0.6464 - val_accuracy: 0.5000 - val_loss: 0.6756
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.8333 - loss: 0.6453 - val_accuracy: 0.5000 - val_loss: 0.6760
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.8333 - loss: 0.6449 - val_accuracy: 0.7500 - val_loss: 0.6763
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.8333 - loss: 0.6437 - val_accuracy: 0.7500 - val_loss: 0.6767
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.8333 - loss: 0.6421 - val_accuracy: 0.7500 - val_loss: 0.6771
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.8333 - loss: 0.6414 - val_accuracy: 0.7500 - val_loss: 0.6774
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.8333 - loss: 0.6405 - val_accuracy: 0.7500 - val_loss: 0.6777
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.8333 - loss: 0.6396 - val_accuracy: 0.7500 - val_loss: 0.6781
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9167 - loss: 0.6379 - val_accuracy: 0.7500 - val_loss: 0.6784
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.6368 - val_accuracy: 0.7500 - val_loss: 0.6787
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.9167 - loss: 0.6361 - val_accuracy: 0.7500 - val_loss: 0.6791
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9167 - loss: 0.6356 - val_accuracy: 0.7500 - val_loss: 0.6794
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9167 - loss: 0.6345 - val_accuracy: 0.7500 - val_loss: 0.6797
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.9167 - loss: 0.6338 - val_accuracy: 0.7500 - val_loss: 0.6800
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.6330 - val_accuracy: 0.7500 - val_loss: 0.6803
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.6322 - val_accuracy: 0.7500 - val_loss: 0.6806
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9167 - loss: 0.6315 - val_accuracy: 0.7500 - val_loss: 0.6808
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.6308 - val_accuracy: 0.7500 - val_loss: 0.6810
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.9167 - loss: 0.6293 - val_accuracy: 0.7500 - val_loss: 0.6812
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.9167 - loss: 0.6284 - val_accuracy: 0.7500 - val_loss: 0.6814
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.8333 - loss: 0.6274 - val_accuracy: 0.7500 - val_loss: 0.6816
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.9167 - loss: 0.6265 - val_accuracy: 0.7500 - val_loss: 0.6817
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.8333 - loss: 0.6255 - val_accuracy: 0.7500 - val_loss: 0.6818
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.8333 - loss: 0.6250 - val_accuracy: 0.7500 - val_loss: 0.6820
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6667 - loss: 0.6252 - val_accuracy: 0.7500 - val_loss: 0.6820
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.7500 - loss: 0.6239 - val_accuracy: 0.7500 - val_loss: 0.6821
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6667 - loss: 0.6224 - val_accuracy: 0.7500 - val_loss: 0.6822
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6667 - loss: 0.6217 - val_accuracy: 0.7500 - val_loss: 0.6823
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6667 - loss: 0.6218 - val_accuracy: 0.7500 - val_loss: 0.6824
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6667 - loss: 0.6204 - val_accuracy: 0.7500 - val_loss: 0.6825
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6667 - loss: 0.6201 - val_accuracy: 0.7500 - val_loss: 0.6826
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6667 - loss: 0.6188 - val_accuracy: 0.7500 - val_loss: 0.6827
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6667 - loss: 0.6188 - val_accuracy: 0.7500 - val_loss: 0.6827
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6667 - loss: 0.6173 - val_accuracy: 0.7500 - val_loss: 0.6828
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6667 - loss: 0.6170 - val_accuracy: 0.7500 - val_loss: 0.6828
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6667 - loss: 0.6161 - val_accuracy: 0.7500 - val_loss: 0.6829
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6667 - loss: 0.6154 - val_accuracy: 0.7500 - val_loss: 0.6829
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6667 - loss: 0.6150 - val_accuracy: 0.7500 - val_loss: 0.6829
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6667 - loss: 0.6148 - val_accuracy: 0.7500 - val_loss: 0.6830
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6667 - loss: 0.6136 - val_accuracy: 0.7500 - val_loss: 0.6830
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6134 - val_accuracy: 0.7500 - val_loss: 0.6830
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5833 - loss: 0.6121 - val_accuracy: 0.7500 - val_loss: 0.6829
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5833 - loss: 0.6116 - val_accuracy: 0.7500 - val_loss: 0.6829
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5833 - loss: 0.6113 - val_accuracy: 0.7500 - val_loss: 0.6829
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6106 - val_accuracy: 0.7500 - val_loss: 0.6829
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5833 - loss: 0.6100 - val_accuracy: 0.7500 - val_loss: 0.6828
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6094 - val_accuracy: 0.7500 - val_loss: 0.6828
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5833 - loss: 0.6092 - val_accuracy: 0.7500 - val_loss: 0.6828
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5833 - loss: 0.6081 - val_accuracy: 0.7500 - val_loss: 0.6827
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5833 - loss: 0.6074 - val_accuracy: 0.7500 - val_loss: 0.6827
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5833 - loss: 0.6078 - val_accuracy: 0.7500 - val_loss: 0.6826
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5833 - loss: 0.6064 - val_accuracy: 0.7500 - val_loss: 0.6826
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5833 - loss: 0.6062 - val_accuracy: 0.7500 - val_loss: 0.6825
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5833 - loss: 0.6056 - val_accuracy: 0.7500 - val_loss: 0.6825
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5833 - loss: 0.6067 - val_accuracy: 0.7500 - val_loss: 0.6824
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.6046 - val_accuracy: 0.7500 - val_loss: 0.6824
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5833 - loss: 0.6036 - val_accuracy: 0.7500 - val_loss: 0.6823
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5833 - loss: 0.6031 - val_accuracy: 0.7500 - val_loss: 0.6822
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5833 - loss: 0.6035 - val_accuracy: 0.7500 - val_loss: 0.6822
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5833 - loss: 0.6022 - val_accuracy: 0.7500 - val_loss: 0.6821
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5833 - loss: 0.6028 - val_accuracy: 0.7500 - val_loss: 0.6820
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5833 - loss: 0.6013 - val_accuracy: 0.7500 - val_loss: 0.6819
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.5833 - loss: 0.6016 - val_accuracy: 0.7500 - val_loss: 0.6818
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5833 - loss: 0.6003 - val_accuracy: 0.7500 - val_loss: 0.6816
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5833 - loss: 0.5995 - val_accuracy: 0.7500 - val_loss: 0.6815
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5833 - loss: 0.5989 - val_accuracy: 0.7500 - val_loss: 0.6814
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5833 - loss: 0.5984 - val_accuracy: 0.7500 - val_loss: 0.6813
Epoch 1/100

ValueError: Cannot take the length of shape with unknown rank.

In [60]:
from tensorflow.keras import optimizers

In [61]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)

In [64]:
model.compile(optimizer = opt,loss='binary_crossentropy', metrics = ['accuracy'])

In [65]:
history_minibatch = model.fit(X_train, y_train, epochs=100, batch_size=100, verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 649ms/step - accuracy: 0.5833 - loss: 0.5979
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.5977
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5974
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5833 - loss: 0.5969
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5963
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5955
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.5947
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5833 - loss: 0.5938
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5928
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5917
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5905
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.5893
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5833 - loss: 0.5880
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.5867
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5853
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.5839
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5833 - loss: 0.5824
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5809
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5833 - loss: 0.5794
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5778
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5762
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.5746
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5833 - loss: 0.5730
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5713
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5696
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5679
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5833 - loss: 0.5662
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.5645
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5628
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5611
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5594
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.5576
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5833 - loss: 0.5559
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5541
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5524
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5506
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5833 - loss: 0.5488
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5833 - loss: 0.5471
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.5453
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.5434
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.5416
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7500 - loss: 0.5398
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.5380
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.5361
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7500 - loss: 0.5343
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7500 - loss: 0.5324
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7500 - loss: 0.5306
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7500 - loss: 0.5287
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.7500 - loss: 0.5268
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7500 - loss: 0.5250
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.5231
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.5212
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.5193
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.5173
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.5154
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.5135
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7500 - loss: 0.5115
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8333 - loss: 0.5095
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8333 - loss: 0.5076
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8333 - loss: 0.5056
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8333 - loss: 0.5036
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8333 - loss: 0.5017
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8333 - loss: 0.4997
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8333 - loss: 0.4977
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.4957
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.4937
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9167 - loss: 0.4917
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9167 - loss: 0.4897
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9167 - loss: 0.4877
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9167 - loss: 0.4857
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.4837
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9167 - loss: 0.4817
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.4797
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.4777
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.4757
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9167 - loss: 0.4737
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9167 - loss: 0.4717
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9167 - loss: 0.4697
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.4677
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.4657
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.4637
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9167 - loss: 0.4618
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.4598
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.4579
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9167 - loss: 0.4559
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.4540
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.4520
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9167 - loss: 0.4501
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.4481
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.4462
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.4443
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.4424
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.9167 - loss: 0.4405
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.4386
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.4366
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.9167 - loss: 0.4347
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.4328
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9167 - loss: 0.4310
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9167 - loss: 0.4291
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.9167 - loss: 0.4272